# Home Work 01
1. Numpy
1. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24
### IS-141 - 15.10.24

## BLOKE №1 (numpy)

1. Импортировать NumPy под именем np

In [1]:
# Write your code
import numpy as np

2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [6]:
# Write your code
vector_zeros = np.zeros(20)
print(vector_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Создать вектор размера 20, заполненный числом 1.75

In [7]:
# Write your code
vector_full = np.full(20, 1.75)
print(vector_full)

[1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75
 1.75 1.75 1.75 1.75 1.75 1.75]


4. Создать вектор со значениями от 4 до 31

In [8]:
# Write your code
vector_arange = np.arange(4, 32)
print(vector_arange)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31]


5. Развернуть вектор (первый становится последним)

In [9]:
# Write your code
vector_reversed = vector_arange[::-1]
print(vector_reversed)

[31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8
  7  6  5  4]


6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [10]:
# Write your code
matrix_3x3 = np.arange(1, 10).reshape(3, 3)
print(matrix_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


7. Создать 3x3 единичную матрицу

In [11]:
# Write your code
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8. Создать 4x4 пустую матрицу

In [12]:
# Write your code
empty_matrix = np.zeros((4, 4))
print(empty_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [14]:
# Write your code
shifted_identity = np.eye(4, k=-1)
print(shifted_identity)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


10. Создать тензор 3x3x3 со случайными значениями

In [15]:
# Write your code
random_tensor = np.random.rand(3, 3, 3)
print(random_tensor)

[[[0.43457307 0.1664722  0.24344954]
  [0.14972192 0.41973088 0.78192712]
  [0.76765879 0.29257997 0.75065377]]

 [[0.94626676 0.56470064 0.38840578]
  [0.80781646 0.62057635 0.18254387]
  [0.07572474 0.11945489 0.97578572]]

 [[0.84922716 0.83873549 0.22333872]
  [0.1210272  0.68698905 0.07659615]
  [0.48326752 0.24230146 0.35615424]]]


11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [17]:
# Write your code
random_matrix = np.random.rand(5, 5)
min_val, max_val = random_matrix.min(), random_matrix.max()
print(min_val)
print(max_val)
print(random_matrix)

0.028193469421243122
0.9983893410421437
[[0.97930696 0.07892483 0.45738531 0.17110894 0.09725037]
 [0.54880996 0.02819347 0.35946654 0.12697494 0.2376002 ]
 [0.11319175 0.66447527 0.6741015  0.84263717 0.3929714 ]
 [0.48240512 0.99838934 0.70659659 0.6278656  0.57723791]
 [0.48749716 0.3838092  0.53928003 0.39649936 0.10839035]]


12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [19]:
# Write your code
random_vector = np.random.rand(50)
mean_value = random_vector.mean()
print(random_vector)
print(mean_value)

[0.9687015  0.066489   0.38116568 0.0933715  0.8743524  0.40141007
 0.3892248  0.6545231  0.88344626 0.72891024 0.34373079 0.47086244
 0.45112932 0.36913879 0.89348232 0.92854732 0.42933712 0.47333887
 0.92530267 0.84441729 0.3175788  0.94366216 0.37715039 0.30342351
 0.78025894 0.330433   0.85839365 0.95919444 0.9610281  0.01071031
 0.62643908 0.33488936 0.88939758 0.93108735 0.92507579 0.74816173
 0.15830871 0.76628659 0.19527958 0.89448218 0.48823923 0.64902952
 0.77259733 0.62609605 0.90019439 0.1604755  0.32469547 0.80679162
 0.86549198 0.91104706]
0.6077356174982266


13. Создать матрицу с 0 внутри, и 1 на границах

In [22]:
# Write your code
def create_bordered_matrix(size=5):
    mat = np.zeros((size, size))
    mat[[0, -1], :] = 1
    mat[:, [0, -1]] = 1
    return mat
bordered_matrix = create_bordered_matrix()
print(bordered_matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [23]:
# Write your code
diag_matrix = np.diag([1, 2, 3, 4], k=-1)
print(diag_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


15. Перемножить матрицы 5x3 и 3x2

In [26]:
# Write your code
mat1 = np.random.rand(5, 3)
mat2 = np.random.rand(3, 2)
matmul_result = np.dot(mat1, mat2)
print(matmul_result)
print(mat2)
print(mat1)

[[0.69394001 1.59828285]
 [0.53323558 0.87691927]
 [0.66182327 1.52306232]
 [0.27811909 0.29562076]
 [0.34163104 0.68641737]]
[[0.7235966  0.97885567]
 [0.05906784 0.97724394]
 [0.26802524 0.15800923]]
[[6.76681256e-01 8.65293032e-01 5.71531094e-01]
 [6.30506138e-01 2.27444714e-01 2.37174727e-01]
 [7.40656663e-01 7.68076885e-01 3.00411949e-01]
 [2.37767759e-01 3.69472356e-04 3.95669160e-01]
 [8.90122165e-02 4.62485345e-01 9.32390165e-01]]


16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12

In [27]:
# Write your code
vec = np.arange(15)
vec[(vec > 6) & (vec < 12)] *= -1
print(vec)

[  0   1   2   3   4   5   6  -7  -8  -9 -10 -11  12  13  14]


17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [28]:
# Write your code
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
C = A * B
print(A)
print(B)
print(C)

[[0.60676794 0.89147414 0.11173092]
 [0.45780143 0.84097247 0.94160956]
 [0.96539521 0.8186217  0.36337683]]
[[0.68987041 0.17218008 0.7268869 ]
 [0.35297054 0.35724133 0.59528621]
 [0.69985025 0.35715098 0.78315408]]
[[0.41859125 0.15349409 0.08121574]
 [0.16159042 0.30043013 0.56052718]
 [0.67563208 0.29237155 0.28458005]]


18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

In [30]:
# Write your code
max_rows = C.max(axis=1)
min_cols = C.min(axis=0)
print(max_rows)
print(min_cols)

[0.41859125 0.56052718 0.67563208]
[0.16159042 0.15349409 0.08121574]


19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [31]:
# Write your code
linspace_vec = np.linspace(0, 1, 10)
print(linspace_vec)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


20. Отсортировать вектор

In [32]:
# Write your code
sorted_vec = np.sort(linspace_vec)
print(sorted_vec)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


21. Проверить, одинаковы ли 2 numpy массива

In [33]:
# Write your code
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
are_equal = np.array_equal(arr1, arr2)
print(arr1)
print(arr2)
print(are_equal)

[1 2 3]
[1 2 3]
True


22. Сделать массив неизменяемым

In [ ]:
# Write your code
arr = np.array([1, 2, 3])
arr.flags.writeable = False


23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [34]:
# Write your code
random_vec = np.random.rand(20)
quantiles = np.quantile(random_vec, [0.1, 0.8])
print(random_vec)
print(quantiles)

[0.37528277 0.42171876 0.92876746 0.18494312 0.70374578 0.37891692
 0.48608092 0.37815379 0.41178222 0.73552872 0.19020569 0.64132856
 0.81405947 0.97975868 0.46124201 0.21250692 0.24786921 0.57231532
 0.54367053 0.96520514]
[0.2102768  0.75123487]


24. Создать массив любой размерности состоящий из int и string

In [35]:
# Write your code
mixed_array = np.array([1, 'text'], dtype=object)
print(mixed_array)

[1 'text']


25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [36]:
# Write your code
int32_min = np.iinfo(np.int32).min
int32_max = np.iinfo(np.int32).max
print(int32_min)
print(int32_max)

-2147483648
2147483647


26. Преобразовать массив из float в int

In [37]:
# Write your code
float_array = np.array([1.5, 2.7])
int_array = float_array.astype(int)
print(int_array)

[1 2]


27. Отнять среднее из каждой строки в матрице

In [39]:
# Write your code
matrix = np.random.rand(3, 3)
matrix_centered = matrix - matrix.mean(axis=1, keepdims=True)
print(matrix)
print(matrix_centered)

[[0.19827535 0.31185461 0.83612126]
 [0.74274179 0.43267744 0.831695  ]
 [0.65949658 0.9782561  0.54694131]]
[[-0.25047506 -0.13689579  0.38737085]
 [ 0.07370371 -0.23636064  0.16265692]
 [-0.06873475  0.25002477 -0.18129002]]


28.

Дана данные из файла.

1,2,3,4,5

6,,,7,8

,,9,10,11

Необходимо прочитать его


In [45]:
# Write your code
from io import StringIO
data = StringIO("1,2,3,4,5\n6,,,7,8\n,,9,10,11")
loaded_data = np.genfromtxt(data, delimiter=',', filling_values=-1)
print(loaded_data)


[[ 1.  2.  3.  4.  5.]
 [ 6. -1. -1.  7.  8.]
 [-1. -1.  9. 10. 11.]]


29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [46]:
# Write your code
sum_squares = np.sum(np.arange(1, 10001)**2)
print(sum_squares)

333383335000


## BLOKE №2 (tensors)

1. Импортируйте pytorch

In [51]:
# Write your code
import torch

2. Создать вектор состящий из 10 элементов

In [52]:
# Write your code
torch_vector = torch.arange(10)
print(torch_vector)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


3. Создать тензор из python list

In [53]:
# Write your code
torch_from_list = torch.tensor([1, 2, 3])
print(torch_from_list)

tensor([1, 2, 3])


4. Создать тензор из np.array

In [54]:
# Write your code
np_array = np.array([4, 5, 6])
torch_from_np = torch.from_numpy(np_array)
print(torch_from_np)

tensor([4, 5, 6])


5. Создать тензор с нормальным распределением

In [60]:
# Write your code
normal_tensor = torch.randn(3, 3)
print(normal_tensor)

tensor([[ 0.9257, -2.3355,  1.1111],
        [ 0.9939,  1.9879,  1.2612],
        [-0.3402,  2.0206, -0.6884]])


6. Создать тензор размером 3х3х3

In [61]:
# Write your code
tensor_3x3x3 = torch.rand(3, 3, 3)
print(tensor_3x3x3)

tensor([[[0.0553, 0.6418, 0.6555],
         [0.7275, 0.4490, 0.4780],
         [0.8767, 0.1354, 0.3209]],

        [[0.1781, 0.3400, 0.1884],
         [0.8770, 0.3055, 0.5839],
         [0.9856, 0.9729, 0.7332]],

        [[0.9730, 0.5003, 0.8349],
         [0.1819, 0.8991, 0.5885],
         [0.3735, 0.9831, 0.7751]]])


7. Создать единичную матрицу размером 4х5

In [62]:
# Write your code
eye_matrix = torch.eye(4, 5)
print(eye_matrix)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])


8. Создать вектор размера 25, заполнить елементами со значениме pi

In [63]:
# Write your code
pi_vector = torch.full((25,), torch.pi)
print(pi_vector)

tensor([3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416])


9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [65]:
# Write your code
matrix_3x3 = torch.arange(9).reshape(3, 3)
multiplied_matrix = matrix_3x3 * 2.5
print(matrix_3x3)
print(multiplied_matrix)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[ 0.0000,  2.5000,  5.0000],
        [ 7.5000, 10.0000, 12.5000],
        [15.0000, 17.5000, 20.0000]])


10. Создать произвольный тензор с типом данных int8

In [67]:
# Write your code
int8_tensor = torch.tensor([-5, 0, 5], dtype=torch.int8)
print(int8_tensor)

tensor([-5,  0,  5], dtype=torch.int8)


11. Изменить тип данных из пункта 10 на int64

In [68]:
# Write your code
int64_tensor = int8_tensor.to(torch.int64)
print(int64_tensor)

tensor([-5,  0,  5])


12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [69]:
# Write your code
random_tensor_4x5 = torch.rand(4, 5)
mean_col2 = random_tensor_4x5[:, 1].mean()
print(random_tensor_4x5)
print(mean_col2)

tensor([[0.9932, 0.1824, 0.0241, 0.6647, 0.9127],
        [0.3250, 0.4325, 0.8173, 0.1564, 0.1823],
        [0.3077, 0.3230, 0.3551, 0.4551, 0.7347],
        [0.6549, 0.5901, 0.0917, 0.9042, 0.6030]])
tensor(0.3820)


13. Создать пустой тензор произвольных размеров

In [70]:
# Write your code
empty_tensor = torch.empty(2, 3)
print(empty_tensor)

tensor([[1.1653e+22, 4.3107e-41, 1.8178e-32],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])


14. Скалярно умножить 2 вектора

In [71]:
# Write your code
vec_a = torch.tensor([1.0, 2.0, 3.0])
vec_b = torch.tensor([4.0, 5.0, 6.0])
dot_product = torch.dot(vec_a, vec_b)
print(dot_product)

tensor(32.)


15. Умножить матрицу на вектор

In [72]:
# Write your code
matrix_3x3 = torch.rand(3, 3)
vector_3 = torch.rand(3)
mv_result = torch.mv(matrix_3x3, vector_3)
print(mv_result)

tensor([0.8352, 1.3545, 1.4546])


16. Перемножить 2D матрицы

In [73]:
# Write your code
mat_a = torch.rand(2, 3)
mat_b = torch.rand(3, 2)
matmul_result = torch.mm(mat_a, mat_b)
print(matmul_result)

tensor([[0.7138, 0.6793],
        [1.2779, 1.0112]])


17. Перемножить 3D тензоры

In [74]:
# Write your code
tensor_3d_a = torch.rand(2, 2, 2)
tensor_3d_b = torch.rand(2, 2, 2)
elementwise_product = tensor_3d_a * tensor_3d_b
print(elementwise_product)

tensor([[[0.5065, 0.2059],
         [0.3137, 0.0501]],

        [[0.0102, 0.0428],
         [0.6621, 0.1368]]])


18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [75]:
# Write your code
normal_vec = torch.randn(10)
filtered_elements = normal_vec[normal_vec > 0.5]
print(filtered_elements)

tensor([0.7133, 0.6092, 0.7753])


19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [76]:
# Write your code
ones_matrix = torch.ones(3, 3)
ones_matrix[:, 0] = 4
print(ones_matrix)

tensor([[4., 1., 1.],
        [4., 1., 1.],
        [4., 1., 1.]])


20. Создать матрицу и вывести сумму по каждой строке

In [77]:
# Write your code
sum_rows = torch.sum(ones_matrix, dim=1)
print(sum_rows)

tensor([6., 6., 6.])


20. Создать матрицу и вывести среднее по каждому столбцу

In [78]:
# Write your code
sum_rows = torch.sum(ones_matrix, dim=1)
print(sum_rows)

tensor([6., 6., 6.])


21. Создать 2 вектора и сконкатенировать по 1 оси

In [80]:
# Write your code
mean_cols = torch.mean(ones_matrix, dim=0)
print(mean_cols)

tensor([4., 1., 1.])


22. Перемножим две большие единичные матрицы.
Сначал на центральном процессоре, затем попробуйте на GPU

In [82]:
# Write your code
if torch.cuda.is_available():
    device = 'cuda'
else:
    device = 'cpu'

# На CPU
cpu_mat1 = torch.eye(1000)
cpu_mat2 = torch.eye(1000)
cpu_result = cpu_mat1 @ cpu_mat2

# На GPU
gpu_mat1 = torch.eye(1000, device=device)
gpu_mat2 = torch.eye(1000, device=device)
gpu_result = gpu_mat1 @ gpu_mat2